#################################################################################
## In customize i made most of the GUI changes, Localization To Hebrew 
## (if the HomeAsistant Dev team not made it already)
## in the past i was using homebridge to connect Homekit and Siri,
## Every Place you see "CUI" the meaning is that i am using home-assistant-custom-ui
## to improve visual info (Currently NOT Working on Lovelace UI)
## https://github.com/andrey-git/home-assistant-custom-ui
##############ה#################################################################
light.white_bulb:
  friendly_name: סלון שמאלית
  icon: mdi:page-layout-sidebar-left
light.yeelight_white_f0b4290e4e68:
  friendly_name:  2 סלון שמאלית
  icon: mdi:page-layout-sidebar-left
light.yeelight_rgb_286c07106e1b:
  friendly_name: 2 סלון ימנית
  hidden: true #????
  icon: mdi:page-layout-sidebar-right
light.living_room_color_bulb:
  icon: mdi:page-layout-sidebar-right
  friendly_name: סלון ימנית
light.philips_bulb:
  friendly_name: חדר שירות
  hidden: false
  icon: mdi:lightbulb-on-outline
light.sonoff_hallway_light:
  friendly_name: מסדרון
  hidden: false
  icon: mdi:track-light
  #CUI -this light is On or Off only
  state_card_mode: no-slider 
light.desk_lamp:
  friendly_name: מנורת שולחן
  icon: mdi:lamp
light.sonoff_light:
  assumed_state: false
  hidden: false
  icon: mdi:ceiling-light
  friendly_name: מנורת מטבח
  #CUI this light is On or Off only so slider is unnecessary
  state_card_mode: no-slider
binary_sensor.switch_158d0000d8c836:
  friendly_name: לחצן חדר שינה
  hidden: true
binary_sensor.motion_sensor_158d0000e62376:
  friendly_name: חיישן תנועה
  device_class: motion
binary_sensor.door_window_sensor_158d0000d834ac:
  friendly_name: דלת חדר שינה
  device_class: door
binary_sensor.door_window_sensor_158d0001b714e9:
  friendly_name: דלת כניסה
  device_class: door
binary_sensor.switch_158d000149b9ab:
  friendly_name: לחצן סלון
  hidden: true
binary_sensor.wall_switch_both_158d0001712d0e:
  friendly_name: לחצן קיר - שניהם
  icon: mdi:arrow-down-bold-box
  hidden: true
binary_sensor.wall_switch_left_158d0001712d0e:
  friendly_name: לחצן קיר - שמאלי
  icon: mdi:arrow-left-bold-box
  hidden: true
binary_sensor.wall_switch_right_158d0001712d0e:
  friendly_name: לחצן קיר - ימני
  icon: mdi:arrow-right-bold-box
  hidden: true
sensor.humidity_158d0001150e4e:
  friendly_name: לחות בבית
  icon: mdi:water-percent
sensor.temperature_158d0001150e4e:
  friendly_name: טמפרטורה בחדר שינה
  unit_of_measurement: "°C"
  # unit_of_measurement: "°מעלות"
  
light.gateway_light_34ce0088d2f7:
  friendly_name: תאורת רכזת
  icon: mdi:album
sensor.illumination_34ce0088d2f7:
  friendly_name: עוצמת אור ברכזת
  unit_of_measurement: 'לומן'
switch.xiaomi_powerstrip:
  friendly_name: מפצל שקעים בסלון
  icon: mdi:power-plug
  #CUI - add more info about the powerstrip on the entitiy
  extra_data_template:
  - ${attributes.load_power}W  ${attributes.temperature}C°  #W C
  device_class: power
group.xiaomi_powerstrip_info:
    friendly_name: מפצל שקעים בסלון
    icon: mdi:power-socket-us
    device_class: power
     
sensor.power_strip_temp:
  friendly_name: טמפרטורת מפצל
  icon: mdi:oil-temperature
  unit_of_measurement: "°C"
   
sensor.power_strip_watt:
  friendly_name: צריכה נוכחית 
  icon: mdi:flash-circle
   
# sensor.power_strip_total_cost:
#   friendly_name: עלות לשעת שימוש
#   icon: mdi:finance
   
media_player.salon:
  friendly_name: פרטנר טיוי
   
media_player.apple_tv:
  friendly_name: אפל טיוי
   
group.alerts:
  friendly_name: התראות
  hidden: true
   
group.historyStat:
  friendly_name: סטטיסטיקה
   
  hidden: false

sensor.date__time:
  friendly_name: תאריך ושעה
   
sun.sun:
  friendly_name: שמש
   
sensor.eliran_iphone_battery_level:
  friendly_name: מצב סוללה -אלירן
   
sensor.eliran_iphone_battery_state:
  friendly_name: סטטוס סוללה -אלירן
   
sensor.shiran_iphone_battery_level:
  friendly_name: מצב סוללה -שירן
   
sensor.shiran_iphone_battery_state:
  friendly_name: סטטוס סוללה -שירן
   
sensor.processor_use:
  friendly_name: ניצול מעבד
   
  icon: mdi:memory
sensor.memory_use_percent:
  friendly_name: ניצול זכרון
  icon: mdi:chip
   
sensor.disk_use_percent_home:
  friendly_name: ניצול אחסון
  icon: mdi:harddisk
   
sensor.since_last_boot:
  friendly_name: זמן מאז אתחול המערכת
  icon: mdi:ubuntu
   
sensor.homeassistant_v2db:
  friendly_name: גודל הדאטה בייס
  icon: mdi:database
   
  unit_of_measurement: 'מגה-ביט'
  
sensor.time_online:
  friendly_name: זמן פעילות הום-אסיסטנט
  icon: mdi:home-assistant
  # 
  unit_of_measurement: 'ימים'
sensor.ssl_hass:
  friendly_name: זמן לסיום SSL HASS
  icon: mdi:certificate
   
  unit_of_measurement: 'ימים'
sensor.ssl_router:
  friendly_name:  זמן לסיום SSL Router
  icon: mdi:certificate
   
  unit_of_measurement: 'ימים'
sensor.ssl_ide:
  friendly_name:  זמן לסיום SSL IDE
  icon: mdi:certificate
   
  unit_of_measurement: 'ימים'
  
sensor.ssl_server:
  friendly_name:  זמן לסיום SSL Server
  icon: mdi:certificate
   
  unit_of_measurement: 'ימים'

sensor.restart_homebridge:
  friendly_name: איתחול הום-ברידג
  icon: mdi:apple
   
device_tracker.eliraniphone:
  friendly_name: אלירן
  hidden: false
   
  device_class: presence
device_tracker.eliran_iphone:
  friendly_name: אלירן לפי מיקום
  hidden: true
   
device_tracker.redminote4israelkes:
  friendly_name: ישראל
   
device_tracker.android983a5bef7ebe50ce:
  friendly_name: סבט
   
device_tracker.shiraniphone:
  friendly_name: שירן
  device_class: presence
   
device_tracker.talamishaimbp:
  friendly_name: טל -מקבוק
   
  hidden: true
device_tracker.desktop4ba97q9:
  friendly_name: המחשב של מתן
  device_class: presence
   
  hidden: true
device_tracker.d0034b143687:
  friendly_name: אפל טיוי
   
device_tracker.partnertv:
  friendly_name: פרטנר טיוי
   
device_tracker.eliranmacbookpro:
  friendly_name: מקבוק פרו -אלירן
   
device_tracker.eliransplewatch:
  friendly_name: שעון -אלירן
   
device_tracker.desktop9cb3035:
  friendly_name: המחשב של שירן
   
device_tracker.chromecast:
  friendly_name: כרוםקאסט
   
group.AllMylights:
  friendly_name: כל התאורה בבית
  device_class: light
  icon: mdi:lighthouse-on
group.Sensors:
  friendly_name: כל החיישנים
   

remote.apple_tv:
  friendly_name: אפל טיוי
   
remote.ir_controller:
  friendly_name: שליטה אינפרא
   
switch.sonoff_xiaomicctv_switch:
  friendly_name: מפסק מצלמת סלון
  icon: mdi:camera-gopro  

sensor.dark_sky_temperature:
  friendly_name: טמפרטורה מקומית
  unit_of_measurement: "°C"
  # unit_of_measurement: "°מעלות"
   
sensor.dark_sky_humidity:
  friendly_name: לחות מקומית

sensor.dark_sky_daily_high_temperature:
  friendly_name: טמפרטורה מקסימלית
  unit_of_measurement: "°C"
  # unit_of_measurement: "°מעלות"

sensor.dark_sky_daily_low_temperature:
  friendly_name:  טמפרטורה מינימלית מקומית
  unit_of_measurement: "°C"
  # unit_of_measurement: "°מעלות"

sensor.dark_sky_summary:
  friendly_name: תחזית
  hidden: true
   
sensor.dark_sky_icon:
  friendly_name: סמל
   
  hidden: true
sensor.dark_sky_apparent_temperature:
  friendly_name: מרגיש כמו
   
  unit_of_measurement: "°מעלות"
  
sensor.dark_sky_precip_probability:
  friendly_name: סיכוי למשקעים
   
  icon: mdi:weather-rainy
sensor.dark_sky_cloud_coverage:
  friendly_name: כיסוי עננים
   
sensor.dark_sky_hourly_summary:
  friendly_name: סיכום שעתי
   
sensor.dark_sky_daily_summary:
  friendly_name: סיכום יומי
   
sensor.dark_sky_pressure:
  hidden: true
   
  
sensor.dark_sky_wind_bearing:
  hidden: true
   
sensor.dark_sky_wind_speed:
  hidden: true
   
sensor.time:
  hidden: true
   
sensor.dark_sky_precip_intensity: 
  hidden: true

automation.set_day_mode_theme_after_sunrise:
  friendly_name: הגדר ערכת נושא ״יום״ לאחר הזריחה
   
automation.set_day_theme_at_startup:
  friendly_name: הגדר ערכת נושא ״יום״ באיתחול
   
automation.set_night_mode_theme_after_sunset:
  friendly_name: הגדר ערכת נושא ״לילה״ לאחר השקיעה
   
automation.set_night_theme_at_startup:
  friendly_name: הגדרת ערכת נושא ״לילה״ באיתחול
   
script.flash_gateway1:
  friendly_name: פלאש 1-רכזת
script.flash_gateway2:
  friendly_name: פלאש-רכזת
   
script.purple_night_light:
  friendly_name: תאורת לילה סגולה -רכזת
   
script.white_night_light:
  friendly_name: תאורת לילה -רכזת
   
script.test_push:
  friendly_name: בדיקת נוטיפיקציה
script.restart_home_assistant:
  friendly_name: איתחול הום-אסיסטנט
   
  icon: mdi:restart
script.reboot_router:
  friendly_name: איתחול ראוטר
  icon: mdi:router-wireless
# script.update_hass:
#  friendly_name: עדכן גירסא להום-אסיסטנט
#   icon: mdi:progress-upload
script.backup_all_os:
  friendly_name: גבה את השרת לאמצעי אחסון
   
  icon: mdi:backup-restore
script.backup_hs_and_move_backup_to_unraid:
  friendly_name: גבה הוםאסיסט והעבר גיבוים שבועיים לכונן
   
  icon: mdi:backup-restore
script.backup_ha_config:
  friendly_name: גבה תיקיית הום-אסיסטנט
   
  icon: mdi:file-restore
script.ac_fan_speed:
  friendly_name: מהירות מאוורר מזגן
  
script.ac_turn_off:
  friendly_name: כבה מזגן

script.ac_turn_on:
  friendly_name: הדלק מזגן

script.turn_off_tv:
  friendly_name: כבה טלויזיה
   
script.turn_on_tv:
  friendly_name: הדלק טלויזיה

script.tv_input:
  friendly_name: קלט טלויזיה

script.tv_vol_down:
  friendly_name: הנמך ווליום טלויזיה

script.tv_vol_up:
  friendly_name: הגבר ווליום טלויזיה

group.shiran_page:
  icon: mdi:human-female
   
sensor.shiran_at_home_yesterday:
  friendly_name: שירן - זמן בבית אתמול
   
  unit_of_measurement: "שעות"
sensor.eliran_at_home_yesterday:
  friendly_name: אלירן - זמן בבית אתמול
   
  unit_of_measurement: "שעות"
sensor.living_room_color_on_today:
  friendly_name: זמן כולל תאורה ימין דולקת היום
   
  unit_of_measurement: "שעות"
sensor.living_room_white_on_today:
  friendly_name: זמן כולל תאורה שמאל דולקת היום
   
  unit_of_measurement: "שעות"
sensor.hallway_white_on_today:
  friendly_name: זמן כולל תאורת מסדרון דולקת היום
   
  unit_of_measurement: "שעות"
sensor.bedroom_desk_on_today:
  friendly_name: זמן כולל תאורת שולחן דולקת היום
   
  unit_of_measurement: "שעות"
sensor.home_door_time_since_open:
  friendly_name: זמן מאז שדלת הבית נפתחה
   
  unit_of_measurement: "שעות"
sensor.kitchen_light_on_today:
  friendly_name: זמן כולל תאורת מטבח דולקת היום
   
  unit_of_measurement: "שעות"

script.ilradio:
    friendly_name: Start Playing
    icon: mdi:play

switch.tv_lg:
  assumed_state: true
  friendly_name: טלויזיה בסלון
  icon: mdi:television
switch.tv_lg_vol:
  assumed_state: true
  friendly_name: ווליום טלויזיה
  icon: mdi:volume-high
   
switch.tv_lg_hdmi1:
  assumed_state: false
  friendly_name: קלט פרטנר טיוי
  icon: mdi:television-guide
   
switch.tv_lg_hdmi2:
  assumed_state: false
  friendly_name: קלט אפל טיוי
  icon: mdi:television-box
   
switch.tv_lg_hdmi3:
  assumed_state: false
  friendly_name: קלט חיצוני
  icon: mdi:video-input-hdmi
   
switch.tv_lg_mute:
  assumed_state: true
  friendly_name: השתק טלויזיה
  icon: mdi:volume-off
group.allmycontrollers:
  friendly_name: כל השלטים
   
gruop.AllmyControllers:
  friendly_name: כל השלטים
   
group.all_switches:
  friendly_name: קבוצה מובנת-כל הלחצנים
  # hidden: ture
   
group.AllMySwitchs:
  friendly_name: כל הלחצנים
  hidden: false
   
switch.bedroom_fan_light: #livolio
  icon: mdi:wall-sconce-flat
  assumed_state: true
  friendly_name: תאורה בחדר שינה
   
  device_class: light

group.all_lights:
   
  device_class: light
# icon: mdi:power-socket-eu
switch._mqtt_pow1:
  friendly_name: מפסק לדוד
  icon: mdi:shower-head
  #CUI
  extra_badge:
    - entity_id: sensor.pow1_current
      attribute: pow1_current
      blacklist_states: 0
    - entity_id: sensor.pow1_watt
      blacklist_states: 0
    - entity_id: device_tracker.sonoffpow1 #sonoff pow1 boiler
      blacklist_states: 'home' #dont show the badge if the device is connected

input_number.slider_boiler:
  friendly_name: זמן להדלקה
  icon: mdi:timer
  unit_of_measurement: 'דקות'
   
  

script.timer_off_boiler:
  icon: mdi:timer-sand
   
group.boiler_setup:
  friendly_name: דוד חכם
  icon: mdi:hot-tub
  #CUI
  extra_badge:
    - entity_id: sensor.pow1_current
      attribute: pow1_current
      blacklist_states: 0
    - entity_id: sensor.pow1_watt
      blacklist_states: 0
    - entity_id: device_tracker.sonoffpow1 #sonoff pow1 boiler
      blacklist_states: 'home' #dont show the badge if the device is connected
  device_class: power
   
group.boiler_page:
   
  icon: mdi:shower-head
sensor.pow1_current:
  friendly_name: צריכה נוכחית 
   
  icon: mdi:flash-circle
sensor.pow1_energy_today:
  friendly_name: צריכה היום
   
  icon: mdi:calendar-today
sensor.pow1_energy_total:
  friendly_name: צריכת חשמל סה״כ
   
  icon: mdi:chart-line
sensor.pow1_energy_yesterday:
  friendly_name: צריכה אתמול
   
  icon: mdi:calendar-clock
sensor.pow1_voltage:
  friendly_name: וולט נוכחי
   
  icon: mdi:flash-circle
sensor.pow1_watt:
  friendly_name: וואט נוכחי
   
  icon: mdi:flash-circle
sensor.pow1_total_cost:
  friendly_name: סך הכל עלות כוללת
   
  icon: mdi:finance


group.POW2_setup:
  friendly_name: מפסק מצלמת מטבח
  icon: mdi:webcam
    #CUI
  extra_badge:
    - entity_id: sensor.pow2_current
      blacklist_states: 0.01
    - entity_id: sensor.pow2_watt
      blacklist_states: 0 
    - entity_id: device_tracker.sonoffpow2 #sonoff pow2 kitchen cctv switch
      blacklist_states: 'home' #dont show the badge if the device is connected
  device_class: power
   
  
switch.mqtt_pow2:
  assumed_state: false
  icon: mdi:webcam
  friendly_name: מפסק מצלמת מטבח
  #CUI
  extra_badge:
    - entity_id: sensor.pow2_current
      blacklist_states: 0.01
    - entity_id: sensor.pow2_watt
      blacklist_states: 0 
    - entity_id: device_tracker.sonoffpow2 #sonoff pow2 kitchen cctv switch
      blacklist_states: 'home' #dont show the badge if the device is connected
   
sensor.pow2_current:
  friendly_name: צריכה נוכחית 
   
  icon: mdi:flash-circle
sensor.pow2_energy_today:
  friendly_name: צריכה היום
   
  icon: mdi:calendar-today
sensor.pow2_energy_total:
  friendly_name: צריכת חשמל סה״כ
   
  icon: mdi:chart-line
sensor.pow2_energy_yesterday:
  friendly_name: צריכה אתמול
   
  icon: mdi:calendar-clock
sensor.pow2_voltage:
  friendly_name: וולט נוכחי
   
  icon: mdi:flash-circle
sensor.pow2_watt:
  friendly_name: וואט נוכחי
   
  icon: mdi:flash-circle
sensor.pow2_total_cost:
  friendly_name: סך הכל עלות כוללת
   
  icon: mdi:finance

sensor.home_assistant_released_version:
  hidden: false
  icon: mdi:new-box
  friendly_name: גרסה עדכנית מפורט
  
sensor.last_HA_released_version:
  hidden: false
  icon: mdi:new-box
  friendly_name: גרסה עדכנית ביותר

sensor.current_version:
  hidden: false
  icon: mdi:home-automation
  friendly_name: גירסא מותקנת
   

# Alarm clock sensors
sensor.alarm_clock_hour:
  friendly_name: 'שעה'
  hidden: true
sensor.alarm_clock_minute:
  friendly_name: 'דקה'
  hidden: true
sensor.alarm_clock_time_long:
  hidden: true
sensor.alarm_clock_time:
  friendly_name: ' שעת שעון המעורר'
  icon: mdi:alarm
# Alarm clock inputs
input_slider.alarm_clock_hour:
  icon: mdi:timer
   
input_slider.alarm_clock_minute:
  icon: mdi:timer
   
input_boolean.alarm_clock_status:
  friendly_name: 'הפעל שעון מעורר'
  icon: mdi:alarm-check
   
sensor.home_to_adoraim:
  friendly_name: זמן הגעה מהבית לאדוריים
  unit_of_measurement: "דקות"
  #CUI
  extra_data_template:
  - ${attributes.route}-דרך


sensor.home_to_otniel:
  friendly_name: זמן הגעה מהבית לעתניאל
  unit_of_measurement: "דקות"
  #CUI
  extra_data_template:
  - ${attributes.route}-דרך

# Alarm clock inputs
input_number.boiler_on_clock_hour:
  icon: mdi:clock-in
   
input_number.boiler_on_clock_minute:
  icon: mdi:timer
   
input_boolean.boiler_on_clock_status:
  friendly_name: 'הפעל זמן הדלקה'
  icon: mdi:alarm-check
   
sensor.boiler_on_clock_time:
  friendly_name: 'זמן הדלקה'
  icon: mdi:clock-start
   

input_number.boiler_off_clock_hour:
  icon: mdi:clock-in
   
input_number.boiler_off_clock_minute:
  icon: mdi:timer
   
input_boolean.boiler_off_clock_status:
  friendly_name: 'הפעל זמן כיבוי'
  icon: mdi:alarm-off
   
sensor.boiler_off_clock_time:
  friendly_name: 'זמן כיבוי'
  icon: mdi:clock-end
   

input_boolean.weather:
  name: מזג האוויר
  custom_ui_state_card: custom-weather-card
  config:
    weather: weather.yweather

vacuum.xiaomi_vacuum:
  friendly_name: 'שואב אבק'
  #CUI - add in the entity the corent fan speed
  extra_data_template:
  - אחוז סוללה ${attributes.battery_level} , ${attributes.fan_speed}-מצב 
  # - %${attributes.battery_level}-סוללה ${attributes.fan_speed}-מצב  

camera.cctv1_snapshot:
  friendly_name: התראת כניסה

binary_sensor.floorplan:
  custom_ui_state_card: state-card-floorplan
  config: !include floorplan.yaml #at config/floorplan.yaml

sensor.latest_ha_backup:
  friendly_name: זמן גיבוי הום-אסיסטנט 
  icon: mdi:timetable
  
group.rates:
  friendly_name: שערי המרה
sensor.dollarusd:
  friendly_name: דולר #Dollar
  icon: mdi:currency-usd
  unit_of_measurement: "₪"
sensor.euroeur:
  friendly_name: יורו  #Euro
  icon: mdi:currency-eur
  unit_of_measurement: "₪"
sensor.poundgbp:
  friendly_name: פאונד בריטי   #GBP
  icon: mdi:currency-gbp
  unit_of_measurement: "₪"
sensor.exchange_date:
  friendly_name:  תאריך עדכון #Exchange Datex

sensor.sonoff_latest_release:
  friendly_name: גירסא אחרונה
  icon: mdi:new-box
script.check_sonoffs_version:
  friendly_name: דרוש מצב גירסאות
  icon: mdi:history
group.Sonoffs_Info:
  friendly_name: מצב גירסאות סונוף
  
group.speedtestnet:
  friendly_name: מהירות גלישה 
sensor.speedtest_download:
  friendly_name: מהירות הורדה
  icon: mdi:download-network
  unit_of_measurement: מגה-ביט #Mbit/s
sensor.speedtest_upload:
  friendly_name: מהירות העלאה
  icon: mdi:upload-network
  unit_of_measurement: מגה-ביט #Mbit/s
sensor.speedtest_ping:
  friendly_name: פינג
  icon: mdi:clock-fast
  unit_of_measurement: מִילִישְׁנִיָּה #Ms
script.update_speedtestnet:
  friendly_name: בצע בדיקה
  icon: mdi:gauge
  
  
sensor.hass: 
  friendly_name: גודל תיקיית גיבויים
script.start_windowsvm:
  friendly_name: התחל וינדוס
  icon: mdi:windows
script.shutdown_windowsvm:
  friendly_name: כבה וינדוס
  icon: mdi:windows
  

sensor.geoip:
  friendly_name: אייפיי חיצוני
  icon: mdi:ethernet
sensor.cpu_temp:
  friendly_name: טמפרטורה מעבד
  icon: mdi:desktop-tower
sensor.gpu_temp:
  friendly_name: טמפרטורה כ.גרפי
  icon: mdi:gpu
climate.living_room:
  friendly_name: מזגן
sensor.sensibo1_temp:
  icon: mdi:oil-temperature
sensor.sensibo1_humidity:
  icon: mdi:water-percent
  
# sensor.hline_1:
# custom_ui_state_card: state-card-hline
# config:
#   width: 90 #--> in percents
#   height: 0 #--> in pixels, adds to bordertop
#   backgroundcolor: white
#   bordertop: '1px solid black'
# sensor.hline_2:
# custom_ui_state_card: state-card-hline
# config:
#   width: 90 #--> in percents
#   height: 0 #--> in pixels, adds to bordertop
#   backgroundcolor: white
#   bordertop: '2mm ridge rgb(135, 206, 250, 1)'
# sensor.hline_3:
# custom_ui_state_card: state-card-hline
# config:
#   width: 65 #--> in percents
#   height: 0 #--> in pixels, adds to bordertop
#   backgroundcolor: white
#   bordertop: '2px double lightskyblue'
# sensor.hline_4:
# custom_ui_state_card: state-card-hline
# config:
#   width: 85 #--> in percents
#   height: 2 #--> in pixels, adds to bordertop
#   backgroundcolor: white
#   bordertop: none
#   backgroundimage: linear-gradient(to right, rgba(0, 0, 0, 0), rgba(135, 206, 250, 0.75), rgba(0, 0, 0, 0))
# sensor.hline_5:
# custom_ui_state_card: state-card-hline
# config:
#   width: 90 #--> in percents
#   height: 0 #--> in pixels, adds to bordertop
#   backgroundcolor: white
#   bordertop: '1px solid black'
# sensor.hline_6:
# custom_ui_state_card: state-card-hline
# config:
#   width: 90 #--> in percents
#   height: 0 #--> in pixels, adds to bordertop
#   backgroundcolor: white
#   bordertop: '1px solid black'