################################################################################
#
#REMOTE - NOT IN USE - Working with Braodlink RM Pro
#All the commads was made for xiaomi IR
#################################################################################
  #for xiaomi  IR controller - NOT IN USE ANYMORE - Switch to BORADLINK RM PRO
  # - platform: xiaomi_miio
  #   name: IR Controller
  #   hidden: False
  #   host: 192.168.1.106
  #   token: !secret XiaomiIRControllerToken

  #   commands:
  #     turn_on_tv: #toggle?????
  #       command:
  #         - raw:Z6VHACsCAABrBgAAZQgAAFARAADuIgAA/J4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0AAAQAAAAAAAQEAAQEBAQEAAAABAAAAAAEBAQABAQEBBQJAA
  #     turn_off_tv:
  #       command:
  #         - raw:Z6VLADYCAABzBgAAuggAAHQRAAAdIwAA3JsAANR1AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0AAAQAAAAAAAQEAAQEBAQEAAAABAAAAAAEBAQABAQEBBQJGAkAA
  #     tv_input:
  #       command:
  #         - raw:Z6VTABMCAABLAgAAbAYAALsIAAB0EQAAHSMAANybAADUdQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFAQEhAQEBAQEhIQEhISEhISEhASEBAQEBAQEhASEhISFhNXE1cTVxNQE
  #     tv_vol_up:
  #       command:
  #         - raw:Z6VLADcCAABzBgAAvAgAAHYRAAAdIwAA3JsAANR1AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0AAAQAAAAAAAQEAAQEBAQEAAQAAAAAAAAEAAQEBAQEBBQJGAkAA
  #     tv_vol_down:
  #       command:
  #         - raw:Z6VLABgCAABGAgAAcwYAALoIAAB0EQAAKSMAANybAADUdQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFAQEhAQEBAQEhIQEhISEhISEhAQEBAQEBAQEhISEhISFhNXE1AQ
  #     ac_turn_on:
  #       command:
  #         - raw:Z6XFAAACAAA2AgAAQQYAAJQGAAATGAAAshwAANccAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABUISEwISEhISEBAREREREREDAhISEwISEhEBAQEREREREhASEhITAhIREhAREQAQEBIREhASERISERIREhASERERARESEhASEhISEhEQEhERERIREhASEBASERIREwETAwYQE
  #         # - raw:Z6XFADQCAABOBgAAogYAAN0XAAC/HAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABDEBAQEBAQEBAAAAAAAAAAABAQEBAQEBAQAAAAAAAAAAAQEBAQEBAQEAAAAAAAAAAAEAAAEBAQEBAAEBAAAAAAAAAQEAAQECAQEAAAEAAAAAAAEAAQABAAABAAEAAQABAgQAA
  #     ac_turn_off:
  #       command:
  #         - raw:Z6XFADMCAABRBgAA/BcAALQcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAyEBAQEBAQEBAAAAAAAAAAABAQEBAQEBAQAAAAAAAAAAAQEBAQEBAQEAAAAAAAAAAAEBAAEBAQEBAAABAAAAAAAAAQEAAQEBAQEAAAEAAAAAAAEAAQABAAABAAEAAQABAQMAA
  #     ac_fan_speed:
  #       command:
  #         - raw:Z6XFACUCAAB5BgAAqBcAAPccAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAyEBAQEBAQEBAAAAAAAAAAABAQEBAQEBAQAAAAAAAAAAAAEAAQEBAQEBAAEAAAAAAAEAAAEBAAEBAAEBAAABAAAAAQEAAQEBAQEAAAEAAAAAAAEAAQABAAABAAEAAQABAQMAA
  #     tv_hdmi1:
  #       command:
  #         - raw:Z6VLADcCAABzBgAAvAgAAHYRAAAdIwAA3JsAANR1AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0AAAQAAAAAAAQEAAQEBAQEAAQAAAAAAAAEAAQEBAQEBBQJGAkAA
  #     tv_hdmi2:
  #       command:
  #         - raw:Z6VLADcCAABzBgAAvAgAAHYRAAAdIwAA3JsAANR1AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0AAAQAAAAAAAQEAAQEBAQEAAQAAAAAAAAEAAQEBAQEBBQJGAkAA
  #     tv_hdmi3:
  #       command:
  #         - raw:Z6VLADcCAABzBgAAvAgAAHYRAAAdIwAA3JsAANR1AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0AAAQAAAAAAAQEAAQEBAQEAAQAAAAAAAAEAAQEBAQEBBQJGAkAA
  
  ###IN USE AT SWITCH.YAML  ###