################################################################################
#
#SHELL COMMANDS
#
##################################################################################
  backup_hass_config: "bash /config/scripts/backup_HASS_config.sh"
  backup_ha_and_move_backup_to_unraid: "bash /config/scripts/backup_HA_and_Move_Backup_To_Unraid.sh"
  reboot_router: "bash /config/scripts/RebootRouter.sh"
  reboot_ap: "bash /config/scripts/RebootAP.sh"
  install_after_update_hass: "bash /config/scripts/install_Comp_after_Update.sh"
  

################################################################################
## NOT
## IN 
## USE
## All the entitys/Code below is working , just not in use in my case 
## (Switch Protocol, Component Etc... ) you can use it :)
################################################################################
  # hassbian_ha_update: "bash /config/scripts/hassbianHA_update.sh"
  # os_reboot: "bash /config/scripts/os_reboot.sh"
  # backup_all_rpi_to_usb: "bash /config/scripts/backup_allRPItousb.sh"
    # start_homebridge: "sudo touch /config/scripts/start_homebridge.sh"